# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Scratch Space
tagline:          'Random thoughts'
description:      'A place to offload thoughts, ideas, and project notes.'
url:              http://popp1nfresh.github.io
baseurl:          /

author:
  name:           'Popp1nFresh'
  url:            https://twitter.com/popp1nfresh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
